config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#landing'

  # Session routes
  get '/login', to: 'sessions#new'
  delete '/logout', to: 'sessions#destroy'

  resources :sessions, only: [:create]

  # User routes
  get '/signup', to: 'users#new', as: 'new_user'

  resources :users, only: [:create]

  # Links routes
  resources :links, only: [:index, :create, :edit, :update]
end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :user

  validates :url, :title, presence: true
  validates :url, format: { with: /\A(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w \.-]*)*\/?\z/ }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :links

  validates :password, :password_confirmation, length: { minimum: 6 }
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.destroy
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :authorized?, only: [:index]

  def index
    link = Link.new
    links = current_user.links.all

    @link_decorator = LinksDecorator.new(link: link, links: links)
  end

  def create
    link = current_user.links.new(link_params)

    if link.save
      flash[:success] = 'Newely submitted link!'
      redirect_to links_path
    else
      links = current_user.links.all
      @link_decorator = LinksDecorator.new(link: link, links: links)
      flash.now[:error] = 'Invalid information provided'
      render :index
    end
  end

  def edit
    @link = Link.find(params[:id])
  end

  def update
    @link = Link.find(params[:id])

    if @link.update(link_params)
      respond_to do |format|
        format.html do
          redirect_to links_path, flash: { success: 'Link updated!' }
        end
        format.json { render json: @link }
      end
    else
      flash.now[:error] = 'Invalid parameters'
      render :edit
    end
  end

  private

  def link_params
    params.require(:link).permit(:url, :title, :read)
  end

  def authorized?
    redirect_to root_path unless current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email])

    if @user && @user.authenticate(params[:session][:password])
      log_in(@user)
      redirect_to links_path
    else
      flash[:error] = 'Invalid email / password combination'
      render :new
    end
  end

  def destroy
    log_out
    redirect_to login_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def landing
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in(@user)
      flash[:success] = 'Thank your for signing up!'
      redirect_to links_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.erb
<header class="header">
  <%= link_to 'Thoughtbox', links_path %>
  <% if current_user %>
    <div class="greeting">
      <small>Welcome, <%= current_user.email %>!</small>
      <%= link_to 'Log Out', logout_path, method: :delete %>
    </div>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Thoughtbox</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body class="container">
  <%= render partial: 'layouts/header' %>

  <% flash.each do |type, msg| %>
    <%= content_tag :div, msg, class: "flash-#{type} flash" %>
  <% end %>

  <%= yield %>

  <%= javascript_include_tag 'application' %>
</body>
</html>

app/views/links/edit.html.erb
<h1>Edit Link</h1>

<%= form_for(@link) do |f| %>
  <%= f.label :url %>
  <%= f.text_field :url %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.submit 'Edit' %>
<% end %>

app/views/links/index.html.erb
<h1>All of the links!</h1>

<h2 class="search">Search:</h2>
<input type="text" id="searchBar">

<h2 class="sort">Sort</h2>
<select name="sort" id="sort">
  <option value="nil" selected="selected">-pick an option-</option>
  <option value="alphabetically">Alphabetically</option>
  <option value="read">Read</option>
  <option value="unread">Unread</option>
</select>

<h2>New Link</h2>
<%= form_for(@link_decorator.link) do |f| %>
  <%= f.label :url, 'URL' %><br>
  <%= f.text_field :url, class: 'input' %><br>

  <%= f.label :title %><br>
  <%= f.text_field :title, class: 'input' %><br>

  <%= f.submit 'Submit', class: 'input' %>
<% end %>

<ul class="links">
  <% if @link_decorator.links.empty? %>
    <p>No links submitted</p>
  <% else %>
    <% @link_decorator.links.each do |link| %>
      <li data-id="<%= link.id %>" class="read-<%= link.read %>">
        <h2>
          <%= link_to link.title, link.url, id: 'linkTitle' %>
          <%= link_to 'Mark as Read', '#', id: 'markAsRead' %>
          <%= link_to 'Mark as Unread', '#', id: 'markAsUnread' %>
          <%= link_to 'Edit', edit_link_path(link) %>
        </h2>
        <h3 id="readStatus">Read: <%= link.read %></h3>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/shared/_errors.html.erb
<% if @user.errors.any? %>
  <h1>
    There are <%= pluralize(@user.errors.count, 'error') %>
  </h1>

  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

app/views/static_pages/landing.html.erb
<h1>Welcome to ThoughtBox!</h1>

<%= link_to 'Login', login_path %>
<%= link_to 'Signup', new_user_path %>

app/views/users/new.html.erb
<%= render partial: 'shared/errors' %>

<h1>New User Sign Up</h1>

<%= form_for(@user) do |f| %>
  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit 'Sign up' %>
<% end %>